project_name: my-fro  # 项目名称，可以随便定义

release:
  github:
    owner: scyslz   # 用你自己的 GitHub 用户名替换
    name: master                # 仓库名称

build:
  goos:
    - linux
    - windows
    - darwin
  goarch:
    - amd64
    - arm64
